# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: C++ CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install -y fd-find libsnappy-dev libxxhash-dev libmimalloc-dev libmsgsl-dev \
            build-essential llvm && \
        sudo ln -sf "$(command -v fdfind)" /bin/fd

    - name: ccache
      uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03 # v1.2.23
      with:
        create-symlink: true

    - name: mold
      uses: rui314/setup-mold@v1

    - name: Save ccache
      run: ccache -s

    - name: Build debug
      run: TERM=xterm ./build.sh -dua

    - name: Build debug with hot reload
      run: TERM=xterm ./build.sh -deua

    - name: Build tests
      run: TERM=xterm ./build.sh -tua

    - name: Run tests
      run: TERM=xterm ./out/main.out_test
